/**
 * @typedef {{
 *   '*--cfg-pubkey': String;
 *   '*--cfg-multiple': Number;
 *   '*--cfg-multiple-min': Number;
 *   '*--cfg-multiple-max': Number;
 *   '*--cfg-confirm-upload': Number;
 *   '*--cfg-img-only': Number;
 *   '*--cfg-accept': String;
 *   '*--cfg-store': Number;
 *   '*--cfg-camera-mirror': Number;
 *   '*--cfg-source-list': String;
 *   '*--cfg-max-local-file-size-bytes': Number;
 *   '*--cfg-thumb-size': Number;
 *   '*--cfg-show-empty-list': Number;
 *   '*--cfg-use-local-image-editor': Number;
 *   '*--cfg-use-cloud-image-editor': Number;
 *   '*--cfg-modal-scroll-lock': Number;
 *   '*--cfg-modal-backdrop-strokes': Number;
 *   '*--cfg-source-list-wrap': Number;
 *   '*--cfg-init-activity': String;
 *   '*--cfg-done-activity': String;
 *   '*--cfg-data-output-console': Number;
 *   '*--cfg-data-output-fire-events': Number;
 *   '*--cfg-data-output-from': String;
 *   '*--cfg-data-output-form-value': Number;
 *   '*--cfg-remote-tab-session-key': String;
 *   '*--cfg-cdn-cname': String;
 *   '*--cfg-secure-signature': String;
 *   '*--cfg-secure-expire': String;
 *   '*--cfg-secure-delivery-proxy': String;
 *   '*--cfg-retry-throttled-request-max-times': Number;
 *   '*--cfg-multipart-min-file-size': Number;
 *   '*--cfg-multipart-chunk-size': Number;
 *   '*--cfg-max-concurrent-requests': Number;
 *   '*--cfg-multipart-max-attempts': Number;
 *   '*--cfg-check-for-url-duplicates': Number;
 *   '*--cfg-save-url-for-recurrent-uploads': Number;
 * }} CssConfigTypes
 */
export {};
