import { TRANSPARENT_PIXEL_SRC } from './lib/transparentPixelSrc.js';

export const STYLES = {
  ':host': {
    display: 'block',
    '--modal-header-opacity': '1',
    '--modal-header-height': 'var(--size-panel-heading)',
    '--modal-toolbar-height': 'var(--size-panel-heading)',
  },
  editor_ON: {
    '--modal-header-opacity': '0',
    '--modal-header-height': '0px',
    '--modal-toolbar-height': 'calc(var(--size-panel-heading) * 2)',
    '--viewer-border-top-radius': 'var(--border-radius-base)',
  },
  editor_OFF: {
    '--modal-header-opacity': '1',
    '--modal-header-height': 'var(--size-panel-heading)',
    '--modal-toolbar-height': 'var(--size-panel-heading)',
    '--viewer-border-top-radius': '0px',
  },
  wrapper: {
    height: '100%',
    position: 'relative',
    display: 'grid',
    gridTemplateRows: 'minmax(var(--l-min-img-height), var(--l-max-img-height)) max-content',
    borderBottomLeftRadius: 'var(--border-radius-base)',
    borderBottomRightRadius: 'var(--border-radius-base)',
    overflow: 'hidden',
    transition: '.3s',
  },
  _mobile: {
    '--l-min-img-height': 'var(--modal-toolbar-height)',
    '--l-max-img-height': '1fr',
    '--l-edit-button-width': '70px',
    '--l-toolbar-horizontal-padding': 'var(--gap-min)',
  },
  _desktop: {
    '--l-min-img-height': 'var(--modal-toolbar-height)',
    '--l-max-img-height': '450px',
    '--l-edit-button-width': '120px',
    '--l-toolbar-horizontal-padding': 'var(--gap-mid-1)',
  },
  viewport: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  image: {
    '--viewer-image-opacity': 1,
    position: 'absolute',
    top: '0px',
    left: '0px',
    display: 'block',
    width: '100%',
    height: '100%',
    objectFit: 'scale-down',
    userSelect: 'none',
    opacity: 'var(--viewer-image-opacity)',
    transform: 'scale(1)',
    boxSizing: 'border-box',
    zIndex: '10',
    pointerEvents: 'auto',
    backgroundColor: 'var(--color-image-background)',
  },
  image_visible_viewer: {
    transition: 'opacity var(--transition-duration-3) ease-in-out, transform var(--transition-duration-4)',
  },
  image_visible_from_cropper: {
    transition: 'transform var(--transition-duration-4), opacity var(--transition-duration-3) steps(1, jump-end)',
  },
  image_visible_from_editor: {
    transition: 'opacity var(--transition-duration-3) ease-in-out, transform var(--transition-duration-4)',
  },
  image_hidden_to_cropper: {
    pointerEvents: 'none',
    '--viewer-image-opacity': 0,
    backgroundImage: `url("${TRANSPARENT_PIXEL_SRC}")`,
    transform: 'scale(1)',
    transition: 'transform var(--transition-duration-4), opacity var(--transition-duration-3) steps(1, jump-end)',
  },
  image_hidden_viewer: {
    pointerEvents: 'none',
    '--viewer-image-opacity': 0,
    transform: 'scale(0.95)',
    transition: 'opacity var(--transition-duration-3) ease, transform var(--transition-duration-4)',
  },
  image_hidden_effects: {
    pointerEvents: 'none',
    '--viewer-image-opacity': 0,
    transform: 'scale(1)',
    transition: 'opacity var(--transition-duration-3) cubic-bezier(.5,0,1,1), transform var(--transition-duration-4)',
  },
  image_container: {
    position: 'relative',
    display: 'block',
    width: '100%',
    height: '100%',
    backgroundColor: 'var(--color-image-background)',
    borderTopLeftRadius: 'var(--viewer-border-top-radius)',
    borderTopRightRadius: 'var(--viewer-border-top-radius)',
    transition: 'var(--transition-duration-3)',
  },
  toolbar: {
    position: 'relative',
    height: 'var(--modal-toolbar-height)',
    transition: '.3s',
  },
  tb_block: {
    display: 'inline-flex',
    gap: 'var(--gap-mid-1)',
  },
  tb_block_align_right: {
    justifyContent: 'flex-end',
  },
  toolbar_content: {
    position: 'absolute',
    left: '0px',
    bottom: '0px',
    width: '100%',
    height: '100%',
    minHeight: 'var(--size-panel-heading)',
    backgroundColor: 'var(--color-fill-contrast)',
    boxSizing: 'border-box',
  },
  toolbar_content__viewer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingLeft: 'var(--l-toolbar-horizontal-padding)',
    paddingRight: 'var(--l-toolbar-horizontal-padding)',
    height: 'var(--size-panel-heading)',
  },
  toolbar_content__editor: {
    display: 'flex',
  },
  list_btn: {
    '--opacity-effect': 0.4,
    color: 'var(--color-primary-accent)',
    display: 'inline-flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: 'var(--size-touch-area)',
    width: 'var(--size-touch-area)',
    cursor: 'pointer',
    opacity: 'var(--opacity-effect)',
    transition: 'opacity var(--transition-duration-2)',
  },
  list_btn__prew: {
    transform: 'scaleX(-1)',
  },
  info_pan: {
    position: 'absolute',
    userSelect: 'none',
  },
  file_type_outer: {
    position: 'absolute',
    userSelect: 'none',
    zIndex: 2,
    display: 'flex',
    transform: 'translateX(-40px)',
    maxWidth: '120px',
  },
  file_type: {
    padding: '4px .8em',
  },
  modal: {
    '--size-modal-width': '840px',
  },
  non_image: {
    transition: 'var(--transition-duration-3)',
    display: 'block',
    width: '100%',
    height: '100%',
  },
  non_image_visible: {
    transform: 'scale(1)',
    opacity: '1',
  },
  non_image_hidden: {
    transform: 'scale(0.95)',
    opacity: '0',
  },
  network_problems_splash: {
    backgroundColor: 'var(--color-fill-contrast)',
    position: 'absolute',
    width: '100%',
    height: '100%',
    zIndex: 4,
    display: 'flex',
    flexDirection: 'column',
  },
  network_problems_content: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    flex: '1',
  },
  network_problems_icon: {
    backgroundColor: 'rgba(var(--rgb-fill-shaded))',
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'rgba(var(--rgb-text-base), 0.6)',
  },
  network_problems_text: {
    marginTop: 'var(--gap-max)',
    fontSize: 'var(--font-size-ui)',
  },
  network_problems_footer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: 'var(--size-panel-heading)',
  },
};

export const COND = {
  img_visible_viewer: 'image image_visible_viewer',
  img_visible_editor: 'image image_visible_from_editor',
  img_visible_cropper: 'image image_visible_from_cropper',
  img_hidden_cropper: 'image image_hidden_to_cropper',
  img_hidden_viewer: 'image image_hidden_viewer',
  img_hidden_effects: 'image image_hidden_effects',
};
