export const STYLES = {
  ':host': {
    position: 'relative',
    height: '100%',
    width: '100%',
  },
  ':host--mobile': {
    '--l-tab-gap': 'var(--gap-mid-1)',
    '--l-slider-padding': 'var(--gap-min)',
    '--l-controls-padding': 'var(--gap-min)',
  },
  ':host--desktop': {
    '--l-tab-gap': 'calc(var(--gap-mid-1) + var(--gap-max))',
    '--l-slider-padding': 'var(--gap-mid-1)',
    '--l-controls-padding': 'var(--gap-mid-1)',
  },
  'toolbar-container': {
    position: 'relative',
    height: '100%',
    width: '100%',
    overflow: 'hidden',
  },
  'sub-toolbar': {
    position: 'absolute',
    width: '100%',
    height: '100%',
    display: 'grid',
    gridTemplateRows: '1fr 1fr',
    transition:
      'opacity var(--transition-duration-3) ease-in-out, transform var(--transition-duration-3) ease-in-out, visibility var(--transition-duration-3) ease-in-out',
    backgroundColor: 'var(--color-fill-contrast)',
  },
  'sub-toolbar--visible': {
    opacity: '1',
    pointerEvents: 'auto',
    transform: 'translateY(0px)',
  },
  'sub-toolbar--top-hidden': {
    opacity: '0',
    pointerEvents: 'none',
    transform: 'translateY(100%)',
  },
  'sub-toolbar--bottom-hidden': {
    opacity: '0',
    pointerEvents: 'none',
    transform: 'translateY(-100%)',
  },
  'controls-row': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: 'var(--l-controls-padding)',
    paddingRight: 'var(--l-controls-padding)',
  },
  'tab-toggles': {
    position: 'relative',
    display: 'grid',
    gridAutoFlow: 'column',
    gridGap: '0px var(--l-tab-gap)',
    height: '100%',
    alignItems: 'center',
  },
  'tab-toggles_indicator': {
    position: 'absolute',
    bottom: '0px',
    left: '0px',
    width: 'var(--size-touch-area)',
    height: '2px',
    backgroundColor: 'var(--color-primary-accent)',
    transform: 'translateX(0px)',
    transition: 'transform var(--transition-duration-3)',
  },
  'tab-content-row': {
    position: 'relative',
  },
  'tab-content': {
    position: 'absolute',
    left: '0px',
    top: '0px',
    width: '100%',
    height: '100%',
    opacity: 0,
    contentVisibility: 'auto',
    display: 'flex',
    overflow: 'hidden',
  },
  'tab-content--visible': {
    opacity: 1,
    pointerEvents: 'auto',
  },
  'tab-content--hidden': {
    opacity: 0,
    pointerEvents: 'none',
  },
  'controls-list_align': {
    display: 'grid',
    gridTemplateAreas: '". inner ."',
    gridTemplateColumns: '1fr auto 1fr',
    paddingLeft: 'var(--gap-max)',
    boxSizing: 'border-box',
    minWidth: '100%',
  },
  'controls-list_inner': {
    gridArea: 'inner',
    display: 'grid',
    gridAutoFlow: 'column',
    gridGap: 'calc((var(--gap-min) - 1px) * 3)',
  },
  'controls-list_last-item': {
    marginRight: 'var(--gap-max)',
  },
  'filter-tooltip_container': {
    position: 'absolute',
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  'filter-tooltip_wrapper': {
    position: 'absolute',
    top: 'calc(-100% - var(--gap-mid-2))',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    pointerEvents: 'none',
  },
  'filter-tooltip': {
    backgroundColor: 'var(--color-text-accent-contrast)',
    color: 'var(--color-text-base)',
    borderRadius: 'var(--border-radius-editor)',
    textTransform: 'uppercase',
    paddingLeft: 'var(--gap-min)',
    paddingRight: 'var(--gap-min)',
    paddingTop: 'calc(var(--gap-min) / 2)',
    paddingBottom: 'calc(var(--gap-min) / 2)',
    fontSize: '0.7em',
    transition: 'var(--transition-duration-3)',
    opacity: 0,
    zIndex: 3,
    letterSpacing: '1px',
  },
  'filter-tooltip_visible': {
    opacity: '1',
    transform: 'translateY(0px)',
  },
  'filter-tooltip_hidden': {
    opacity: '0',
    transform: 'translateY(100%)',
  },
  slider: {
    paddingLeft: 'var(--l-slider-padding)',
    paddingRight: 'var(--l-slider-padding)',
  },
};

export const COND = {
  operation_tooltip_visible: 'filter-tooltip filter-tooltip_visible',
  operation_tooltip_hidden: 'filter-tooltip filter-tooltip_hidden',
};
