name: e2e-tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        working-directory: ./
        run: npm ci
      - name: Install playwright deps
        run: npx playwright install --with-deps chromium
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - name: Run e2e tests
        run: npm run test:e2e
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-tests
          path: |
            tests/__screenshots__/**
